# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b328b448f7b3dbc65a193e6b9b8f16e62020053de3d0376f381efbe5abccaf8174912017465a438edf3e9cd0210cd5c0fe9e7740470f639d97047703be497a10

test:
  secret_key_base: ff0a90ff02bd9b7d3a67d2c463855dfdb0f4979d5cc2f786f799eb339d208c5e5118d1a99fbbe5d89e506b0441ad3f841bef7ab8b9ac76e0cac244ffc79ed05c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
